export const SAMPLE_LOGS = [
  {
    id: '1741896001000',
    where: 'Supermarket',
    timeOfDay: 'Morning',
    leadUp:
      'Checking out at the busy till with loud beeping and bright lights.',
    whatHappened:
      'Child covered ears, started screaming and tried to run toward the exit.',
    after: 'Moved to the car immediately; sat in silence for 10 minutes.',
    logDate: '2026-03-01T10:30:00Z',
    tags: ['Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Ear defenders / noise-reducing headphones': 'Effective',
      'Movement break': 'Not used',
      'Deep pressure input': 'Effective',
    },
  },
  {
    id: '1741896002000',
    where: 'Bedroom',
    timeOfDay: 'Evening',
    leadUp:
      'Getting ready for bed; transition from playing with Lego to brushing teeth.',
    whatHappened:
      "Refusal to move, throwing Lego bricks across the room and shouting 'No'.",
    after:
      'Used timer and deep pressure; child eventually agreed to brush teeth.',
    logDate: '2026-03-01T19:45:00Z',
    tags: ['Routine', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Visual timetable': 'Not effective',
      'Timers or countdown clocks': 'Effective',
      'Weighted blanket': 'Effective',
    },
  },
  {
    id: '1741896003000',
    where: 'School Gates',
    timeOfDay: 'Morning',
    leadUp: 'Arriving at school; very crowded with other parents and children.',
    whatHappened:
      'Clung to my leg, crying quietly and refusing to enter the building.',
    after:
      'Teacher came out with a transition toy; child went in after 5 minutes.',
    logDate: '2026-03-02T08:50:00Z',
    tags: ['Social Connection', 'Communication'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Transition warnings': 'Effective',
      'Social story': 'Not effective',
      'Co-regulation with trusted adult': 'Effective',
    },
  },
  {
    id: '1741896004000',
    where: 'Kitchen',
    timeOfDay: 'Morning',
    leadUp:
      'I turned on the blender to make a smoothie while child was eating breakfast.',
    whatHappened:
      'Instant meltdown; child dropped to the floor and started sobbing.',
    after:
      'Turned off blender; provided cuddles and noise-canceling headphones.',
    logDate: '2026-03-02T07:30:00Z',
    tags: ['Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Ear defenders / noise-reducing headphones': 'Effective',
      'Calm-down space': 'Effective',
    },
  },
  {
    id: '1741896005000',
    where: 'Park',
    timeOfDay: 'Afternoon',
    leadUp: 'Another child took the swing that they were waiting for.',
    whatHappened: 'Pushed the other child and started yelling loudly.',
    after: 'Left the park; discussed the situation using visuals once home.',
    logDate: '2026-03-03T15:00:00Z',
    tags: ['Social Connection', 'Self-Regulated'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Social story': 'Not used',
      'Extra processing time': 'Effective',
      'Comic strip conversations': 'Effective',
    },
  },
  {
    id: '1741896006000',
    where: 'Living Room',
    timeOfDay: 'Evening',
    leadUp: 'Tablet time ended; I gave a 2-minute warning.',
    whatHappened:
      'Threw the tablet on the sofa and started kicking the cushions.',
    after: 'Used a heavy lap pad and sat quietly until the breathing slowed.',
    logDate: '2026-03-03T17:30:00Z',
    tags: ['Routine', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Now & Next board': 'Effective',
      'Weighted lap pad': 'Effective',
      'Timers or countdown clocks': 'Not effective',
    },
  },
  {
    id: '1741896007000',
    where: 'Bedroom',
    timeOfDay: 'Morning',
    leadUp: 'Woke up twice during the night; very tired this morning.',
    whatHappened:
      'Total refusal to get dressed; crying over the texture of the socks.',
    after:
      "Switched to seamless socks and allowed 10 mins of 'decompression' time.",
    logDate: '2026-03-04T07:15:00Z',
    tags: ['Sleep', 'Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Comfortable clothing': 'Effective',
      'Quiet decompression time': 'Effective',
      'Adult prompting for task initiation': 'Not effective',
    },
  },
  {
    id: '1741896008000',
    where: 'Hallway',
    timeOfDay: 'Morning',
    leadUp: "Putting on shoes to go to a doctor's appointment.",
    whatHappened:
      "Child sat on the floor and went limp; wouldn't communicate at all.",
    after: 'Showed the visual planner for the day; child seemed relieved.',
    logDate: '2026-03-04T09:00:00Z',
    tags: ['Communication', 'Routine'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Visual planners': 'Effective',
      'Communication cards': 'Effective',
      'Reduced language': 'Effective',
    },
  },
  {
    id: '1741896009000',
    where: 'Dining Room',
    timeOfDay: 'Afternoon',
    leadUp: 'Grandparents visited; lots of overlapping conversations.',
    whatHappened:
      'Child started humming loudly and spinning in circles, then hid under the table.',
    after: 'Allowed child to go to their room with a fidget tool.',
    logDate: '2026-03-05T13:00:00Z',
    tags: ['Social Connection', 'Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Quiet space / low stimulation area': 'Effective',
      'Fidget tool / sensory object': 'Effective',
      'Recovery time after social demand': 'Effective',
    },
  },
  {
    id: '1741896010000',
    where: 'Car',
    timeOfDay: 'Afternoon',
    leadUp: 'Stuck in traffic for 40 minutes on the way home from school.',
    whatHappened:
      "Kicking the back of the driver's seat and crying 'I want out'.",
    after: 'Gave a sensory object to hold; played calming music.',
    logDate: '2026-03-05T16:15:00Z',
    tags: ['Self-Regulated', 'Routine'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Fidget tool / sensory object': 'Effective',
      'Transition warnings': 'Not effective',
      'Reduced language': 'Effective',
    },
  },
  {
    id: '1741896011000',
    where: 'Bathroom',
    timeOfDay: 'Evening',
    leadUp: 'Hair washing during bath time.',
    whatHappened:
      'Extreme distress; screaming and trying to climb out of the bath.',
    after: 'Dried off quickly; wrapped in a warm towel and held tightly.',
    logDate: '2026-03-06T18:45:00Z',
    tags: ['Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Deep pressure input': 'Effective',
      'Quiet decompression time': 'Effective',
    },
  },
  {
    id: '1741896012000',
    where: 'Playground',
    timeOfDay: 'Morning',
    leadUp: 'End of play time; whistle blew to go back inside.',
    whatHappened:
      'Child ran to the far end of the field and refused to come back.',
    after: "Adult walked over and used 'First/Then' card.",
    logDate: '2026-03-07T10:45:00Z',
    tags: ['Routine', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'First/Then cards': 'Effective',
      'Visual timetable': 'Effective',
      'Adult prompting for task initiation': 'Effective',
    },
  },
  {
    id: '1741896013000',
    where: 'Kitchen',
    timeOfDay: 'Evening',
    leadUp: 'Asked child to put their plate in the sink.',
    whatHappened:
      'Child stared blankly for 30 seconds, then got angry when I repeated the instruction.',
    after:
      'Realized they needed more time; I stepped away and they did it alone.',
    logDate: '2026-03-07T17:15:00Z',
    tags: ['Communication', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Extra processing time': 'Effective',
      'One instruction at a time': 'Effective',
      'Modelling expected language': 'Not used',
    },
  },
  {
    id: '1741896014000',
    where: 'Library',
    timeOfDay: 'Morning',
    leadUp: "A group of toddlers started a 'sing-along' session nearby.",
    whatHappened:
      'Child started rocking back and forth and making a low growling noise.',
    after: 'Quickly left the area; sat on a bench outside.',
    logDate: '2026-03-08T11:00:00Z',
    tags: ['Sensory', 'Social Connection'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Ear defenders / noise-reducing headphones': 'Effective',
      'Movement break': 'Effective',
      'Quiet space / low stimulation area': 'Effective',
    },
  },
  {
    id: '1741896015000',
    where: 'Bedroom',
    timeOfDay: 'Morning',
    leadUp: 'Changing from pajamas into school uniform.',
    whatHappened: "Child upset because the school jumper felt 'scratchy'.",
    after: 'Put a soft t-shirt underneath; child settled down.',
    logDate: '2026-03-09T07:45:00Z',
    tags: ['Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Comfortable clothing': 'Effective',
      'Compression clothing': 'Effective',
    },
  },
  {
    id: '1741896016000',
    where: 'Kitchen',
    timeOfDay: 'Evening',
    leadUp: 'Dinner was served; carrots were touching the pasta.',
    whatHappened:
      'Child pushed the plate off the table; pasta went everywhere.',
    after: 'Cleaned up without speaking; provided a new plate with dividers.',
    logDate: '2026-03-09T18:00:00Z',
    tags: ['Sensory', 'Self-Regulated'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Reduced language': 'Effective',
      Checklists: 'Not used',
      'Co-regulation with trusted adult': 'Effective',
    },
  },
  {
    id: '1741896017000',
    where: 'Classroom',
    timeOfDay: 'Morning',
    leadUp: 'The teacher changed the seat plan unexpectedly.',
    whatHappened:
      'Child sat at the new desk but put their head down and refused to work.',
    after:
      'Teacher provided a visual planner showing the day would still be the same.',
    logDate: '2026-03-10T09:30:00Z',
    tags: ['Routine', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Visual planners': 'Effective',
      'Transition warnings': 'Not effective',
      'Social story': 'Effective',
    },
  },
  {
    id: '1741896018000',
    where: 'Hallway',
    timeOfDay: 'Afternoon',
    leadUp: 'Coming home from school; lots of mud on shoes.',
    whatHappened:
      'Upset when told shoes had to come off before entering the lounge.',
    after: "Cuddled in the hallway until the 'big feelings' passed.",
    logDate: '2026-03-10T15:45:00Z',
    tags: ['Self-Regulated', 'Routine'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Co-regulation with trusted adult': 'Effective',
      'Recovery time': 'Effective',
      'Emotion cards or visuals': 'Not used',
    },
  },
  {
    id: '1741896019000',
    where: 'Doctor Office',
    timeOfDay: 'Morning',
    leadUp: 'Waiting for 20 minutes in a small, warm room.',
    whatHappened:
      'Child began pacing and touching all the medical equipment on the desk.',
    after: 'Gave child a wobble cushion to sit on; provided a fidget.',
    logDate: '2026-03-11T11:20:00Z',
    tags: ['Sensory', 'Executive Function'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Balance cushion / wobble cushion': 'Effective',
      'Fidget tool / sensory object': 'Effective',
      'Movement break': 'Effective',
    },
  },
  {
    id: '1741896020000',
    where: 'Living Room',
    timeOfDay: 'Afternoon',
    leadUp: 'Asking the child what they wanted for lunch.',
    whatHappened:
      "Child yelled 'I don't know' and started hitting their own head.",
    after: 'Stopped asking questions; used choice cards instead.',
    logDate: '2026-03-11T12:30:00Z',
    tags: ['Communication'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Communication cards': 'Effective',
      'Visual supports / symbols': 'Effective',
      'Reduced language': 'Effective',
    },
  },
  {
    id: '1741896021000',
    where: 'Bedroom',
    timeOfDay: 'Night time',
    leadUp: 'Lights out; time to go to sleep.',
    whatHappened: "Crying that the room was 'too dark' and 'scary'.",
    after: 'Added a dim red nightlight; stayed nearby until child slept.',
    logDate: '2026-03-11T20:00:00Z',
    tags: ['Sleep', 'Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Reduced lighting': 'Effective',
      'Weighted blanket': 'Effective',
      'Predictable recovery routines': 'Effective',
    },
  },
  {
    id: '1741896022000',
    where: 'School Hall',
    timeOfDay: 'Morning',
    leadUp: 'Assembly with the whole school; very loud singing.',
    whatHappened: 'Child tried to crawl under the chairs and began to cry.',
    after:
      'Staff moved child to a quiet workspace for the rest of the morning.',
    logDate: '2026-03-12T10:00:00Z',
    tags: ['Sensory', 'Social Connection'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Ear defenders / noise-reducing headphones': 'Effective',
      'Quiet workspace': 'Effective',
      'Reduced group size': 'Effective',
    },
  },
  {
    id: '1741896023000',
    where: 'Kitchen',
    timeOfDay: 'Afternoon',
    leadUp: 'The wrong color cup was given for juice.',
    whatHappened: 'Child threw the cup across the kitchen; juice everywhere.',
    after: 'Sat on the floor together until calm; child helped clean up later.',
    logDate: '2026-03-12T16:30:00Z',
    tags: ['Self-Regulated', 'Routine'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Emotion cards or visuals': 'Effective',
      'Co-regulation with trusted adult': 'Effective',
      'Recovery time': 'Effective',
    },
  },
  {
    id: '1741896024000',
    where: 'Supermarket',
    timeOfDay: 'Afternoon',
    leadUp: 'Walking through the freezer aisle (very cold).',
    whatHappened: 'Child became very stiff and refused to keep walking.',
    after: "Put on child's hoodie; child felt better immediately.",
    logDate: '2026-03-13T14:00:00Z',
    tags: ['Sensory'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Comfortable clothing': 'Effective',
      'Fidget tool / sensory object': 'Not used',
    },
  },
  {
    id: '1741896025000',
    where: 'Living Room',
    timeOfDay: 'Evening',
    leadUp: 'Grandparents leaving after a long day of play.',
    whatHappened:
      'Child hid behind the sofa and refused to say goodbye; crying loudly.',
    after: 'Allowed quiet time in the sensory swing.',
    logDate: '2026-03-13T17:00:00Z',
    tags: ['Social Connection', 'Masking / Energy Management Supports'],
    impactLevel: null,
    mediaUri: null,
    strategies: {
      'Sensory swing': 'Effective',
      'Recovery time after social demand': 'Effective',
      'Quiet decompression time': 'Effective',
    },
  },
];
